name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag oai-pmh-view:$(date +%s)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      run: docker login ghcr.io -u patrickfuhrmann-HTWBerlin --password ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push Docker image
      run: docker buildx build  --tag ghcr.io/patrickfuhrmann-htwberlin/oai-pmh-view:4.4 --push .
