name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag oai-pmh-view:$(date +%s)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push Docker image
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        REPO_USER=$(echo ${{ github.repository_owner}} | tr '[:upper:]' '[:lower:]')
        docker build -t oai-pmh-view:5.5 .
        docker tag oai-pmh-view:5.5 ghcr.io/$REPO_USER/$REPO_NAME:5.5
        docker push ghcr.io/$REPO_USER/$REPO_NAME:5.5
